id = "catppuccin"
name = "Catppuccin"
schema_version = 1
version = "0.2.23"
authors = ["Catppuccin <releases@catppuccin.com>"]
description = "ðŸ¦€ Soothing pastel theme for Zed"
repository = "https://github.com/catppuccin/zed"
