id = "catppuccin"
name = "Catppuccin"
schema_version = 1
version = "0.2.20"
authors = ["Catppuccin <releases@catppuccin.dev>"]
description = "ðŸ¦€ Soothing pastel theme for Zed"
repository = "https://github.com/catppuccin/zed"
